# tests/conftest.py
"""
Shared fixtures/helpers for the point-process test suite, organized into
four layers of increasing scope and decreasing diagnostic precision:

  Layer 0 (test_layer0_known_answer.py):
      Hand-computed likelihood values, no simulation, no optimizer.
      Localizes bugs to a specific formula in _nll.

  Layer 1 (test_layer1_integral_consistency.py):
      Closed-form `integral_func`/`func` pairs cross-checked against
      scipy.integrate.quad of the SAME pointwise function. Catches
      disagreement between `evaluate` and `integrate` within one kernel.

  Layer 2 (test_layer2_independent_simulator.py):
      Data generated by a FROM-SCRATCH reference simulator that does NOT
      call simulate_stream/RateKernel/HistoryKernel at all, fit with the
      codebase's normal fit()/fit_multistart(). Directly answers "could
      simulate_stream and _nll share a bug and both be wrong the same way,"
      since this simulator shares no code with either.

  Layer 3 (test_layer3_simulation_compensator_consistency.py):
      Data generated via the codebase's OWN simulate_stream at TRUE
      (not fitted) parameters, checked via time_rescaling/Ogata's theorem
      for Uniform(0,1) residuals. No optimizer involved. Catches
      disagreement between simulate_stream's pointwise evaluate() calls
      and cumulative_integrated_intensity's integrate() calls.

  Layer 4 (test_layer4_parameter_recovery.py):
      End-to-end: simulate via simulate_stream, refit from scratch, compare
      to ground truth. Assumes Layers 0-3 already pass; this layer's job is
      to catch optimizer/parametrization/plumbing bugs, NOT likelihood
      correctness (see conversation notes on why simulate-then-fit alone is
      an insufficient test).

IMPORTANT CAVEAT ON TOLERANCES: only Layer 0's tolerances are "exact match"
(deterministic, no simulation noise). Layers 2-4 involve stochastic
simulation, so tolerances are necessarily loose and were calibrated by
inspection at the fixed seeds used here -- if you change a seed, a dataset
size, or add a parameter, re-inspect the actual |diff| vs tolerance before
trusting a pass/fail, per the assert_recovered docstring below.
"""
from typing import Dict, List, Optional

import numpy as np
import pytest

from BehaviorScreen.point_process.dataset import PointProcessDataset


# =============================================================================
# Dataset construction helpers
# =============================================================================

def make_scaffold_dataset(
    num_fish: int, num_trials: int, duration_s: float, binning_dt: float = 0.05
) -> PointProcessDataset:
    """
    An EMPTY dataset shell (no events yet) with every (fish, trial) marked
    active -- provides the (duration_s, mask, ids) context simulate_stream
    needs, before any events exist to put in it.
    """
    return PointProcessDataset(
        event_times=np.array([], dtype=float),
        event_trials_idx=np.array([], dtype=int),
        event_fish_idx=np.array([], dtype=int),
        fish_trial_mask=np.ones((num_fish, num_trials), dtype=bool),
        fish_ids=np.array([f"fish_{i}" for i in range(num_fish)]),
        duration_s=duration_s,
        binning_dt=binning_dt,
    )


def simulate_dataset_from_model(
    model,
    scaffold: PointProcessDataset,
    rng: np.random.Generator,
    fish_gains: Optional[np.ndarray] = None,
) -> PointProcessDataset:
    """
    Simulate a full dataset by calling model.simulate_stream(scaffold, t_idx,
    gain, rng) for every active (fish, trial) pair in `scaffold`.

    PRECONDITION: model.set_params(...) must already have been called with
    the parameters you want to simulate FROM -- every simulate_stream
    implementation in this codebase reads self.params_ internally, not an
    explicit argument.

    fish_gains: optional (num_fish,) array of per-fish multiplicative gain
    draws (a frailty realization), SHARED across all of that fish's trials
    -- matching the modeling assumption that g_f is a fish-level, not a
    fish-trial-level, random effect. Defaults to gain=1 for every fish (no
    frailty).
    """
    if fish_gains is None:
        fish_gains = np.ones(scaffold.num_fish)

    times, trials, fish = [], [], []
    for f_idx in range(scaffold.num_fish):
        for t_idx in range(scaffold.num_trials):
            if not scaffold.fish_trial_mask[f_idx, t_idx]:
                continue
            ev = model.simulate_stream(scaffold, t_idx, float(fish_gains[f_idx]), rng)
            if len(ev):
                times.append(np.asarray(ev, dtype=float))
                trials.append(np.full(len(ev), t_idx, dtype=int))
                fish.append(np.full(len(ev), f_idx, dtype=int))

    event_times = np.concatenate(times) if times else np.array([], dtype=float)
    event_trials_idx = np.concatenate(trials) if trials else np.array([], dtype=int)
    event_fish_idx = np.concatenate(fish) if fish else np.array([], dtype=int)

    return PointProcessDataset(
        event_times=event_times,
        event_trials_idx=event_trials_idx,
        event_fish_idx=event_fish_idx,
        fish_trial_mask=scaffold.fish_trial_mask,
        fish_ids=scaffold.fish_ids,
        duration_s=scaffold.duration_s,
        binning_dt=scaffold.binning_dt,
    )


def dataset_from_streams(
    streams: List[List[np.ndarray]], duration_s: float, num_trials: int
) -> PointProcessDataset:
    """
    Build a PointProcessDataset from a nested list `streams[fish_idx][trial_idx]
    -> event_times array` -- used by Layer 2's independent-simulator tests,
    which don't go through simulate_dataset_from_model at all (that helper
    calls model.simulate_stream; Layer 2 deliberately avoids the model
    entirely on the generation side).
    """
    times, trials, fish = [], [], []
    for f_idx, per_trial_events in enumerate(streams):
        for t_idx, ev in enumerate(per_trial_events):
            if len(ev):
                times.append(np.asarray(ev, dtype=float))
                trials.append(np.full(len(ev), t_idx, dtype=int))
                fish.append(np.full(len(ev), f_idx, dtype=int))
    return PointProcessDataset(
        event_times=np.concatenate(times) if times else np.array([], dtype=float),
        event_trials_idx=np.concatenate(trials) if trials else np.array([], dtype=int),
        event_fish_idx=np.concatenate(fish) if fish else np.array([], dtype=int),
        fish_trial_mask=np.ones((len(streams), num_trials), dtype=bool),
        fish_ids=np.array([f"fish_{i}" for i in range(len(streams))]),
        duration_s=duration_s,
    )


# =============================================================================
# Assertion / introspection helpers
# =============================================================================

def assert_recovered(name: str, fitted: float, true: float, rtol: float = 0.15, atol: float = 0.02):
    """
    Generic |fitted - true| <= atol + rtol*|true| check with a readable
    failure message. NOTE: this combines relative and absolute tolerance
    (like np.isclose) rather than pure relative, so tests on true values
    near zero (e.g. small dip depths) don't require an absurdly loose rtol.
    """
    diff = abs(fitted - true)
    tol = atol + rtol * abs(true)
    assert diff <= tol, (
        f"Parameter recovery failed for '{name}': fitted={fitted:.4f}, true={true:.4f}, "
        f"|diff|={diff:.4f} > tol={tol:.4f} (rtol={rtol}, atol={atol})"
    )
    

def assert_stream_calibrated(model, dataset, min_p_value: float = 0.01):
    """
    Uses combined_stream_gap_calibration_test (Fisher-combined per-stream
    GAP-based uniformity p-values), valid for BOTH baseline-only and
    history-dependent processes -- see that method's docstring, and
    per_stream_gap_pvalue's docstring for why the order-statistic
    alternative is invalid for Hawkes/Renewal specifically.
    """
    calib = model.combined_stream_gap_calibration_test(dataset)
    assert calib["combined_p_value"] > min_p_value, (
        f"Fisher-combined GAP calibration p-value={calib['combined_p_value']:.4g} "
        f"(n_streams_tested={calib['n_streams_tested']}) -- simulate_stream and "
        f"cumulative_integrated_intensity/compensator machinery disagree for {model.name}."
    )


def params_dict(model) -> Dict[str, float]:
    return dict(zip(model.param_names, model.params_))


class DummyFitResult:
    """
    Minimal stand-in for scipy.optimize.OptimizeResult, used by Layer 3
    tests that evaluate time_rescaling() at TRUE parameters WITHOUT ever
    calling fit()/fit_multistart() -- some downstream consumers (e.g.
    diagnose()'s summary panel reading .log_likelihood) expect
    model.fit_result.fun to exist. Setting fun=nan is deliberate: it makes
    it obvious if a test accidentally relies on a real log-likelihood value
    from this dummy rather than computing one properly.
    """
    fun = float("nan")


# =============================================================================
# Common fixtures
# =============================================================================

@pytest.fixture
def rng_factory():
    """Returns a function that builds a fresh, seeded np.random.Generator --
    use rng_factory(seed) rather than a single shared fixture so each test
    can pick its own seed inline and stay independently reproducible/
    greppable without fixture indirection hiding the seed value."""
    def _make(seed: int) -> np.random.Generator:
        return np.random.default_rng(seed)
    return _make