"""
Shared fixtures/helpers for the point-process test suite.

Layer 0: deterministic known-answer likelihood/compensator tests
    No simulation and usually no optimizer. These localize algebra and
    state-update errors.

Layer 1: intensity/integral consistency
    Pointwise kernel functions are integrated by an independent numerical
    method and compared with the production integration path.

Layer 2: independent-simulator tests
    Data are generated without using the production simulator and are then
    evaluated/fitted using the production likelihood.

Layer 3: known-parameter simulator/compensator consistency
    Data are generated by the production simulator at known parameters and
    assessed using censoring-aware time-rescaling calibration. No fitting is
    performed. This checks that simulation and compensation implement the
    same process.

Layer 4: end-to-end parameter recovery
    Data are generated by the production simulator and refitted. These tests
    primarily exercise optimization, parametrization, and wrapper plumbing.

Layer 5: parametric-bootstrap GOF
    Tests the final simulate -> refit -> diagnose pipeline, including bootstrap
    statistics, support masks, envelopes, and detection of clear
    misspecification.

Only Layers 0 and 1 should generally use near-machine-precision assertions.
Stochastic layers use fixed seeds as regression tests, not as formal
hypothesis tests.
"""

from typing import Dict, List, Optional

import numpy as np
import pytest

from BehaviorScreen.point_process.dataset import PointProcessDataset

# =============================================================================
# Dataset construction helpers
# =============================================================================


def make_scaffold_dataset(
    num_fish: int, num_trials: int, duration_s: float, binning_dt: float = 0.05
) -> PointProcessDataset:
    """
    An EMPTY dataset shell (no events yet) with every (fish, trial) marked
    active -- provides the (duration_s, mask, ids) context simulate_stream
    needs, before any events exist to put in it.
    """
    return PointProcessDataset(
        event_times=np.array([], dtype=float),
        event_trials_idx=np.array([], dtype=int),
        event_fish_idx=np.array([], dtype=int),
        fish_trial_mask=np.ones((num_fish, num_trials), dtype=bool),
        fish_ids=np.array([f"fish_{i}" for i in range(num_fish)]),
        duration_s=duration_s,
        binning_dt=binning_dt,
    )


def simulate_dataset_from_model(
    model,
    scaffold: PointProcessDataset,
    rng: np.random.Generator,
    fish_gains: Optional[np.ndarray] = None,
) -> PointProcessDataset:
    """
    Simulate a full dataset by calling model.simulate_stream(scaffold, t_idx,
    gain, rng) for every active (fish, trial) pair in `scaffold`.

    PRECONDITION: model.set_params(...) must already have been called with
    the parameters you want to simulate FROM -- every simulate_stream
    implementation in this codebase reads self.params_ internally, not an
    explicit argument.

    fish_gains: optional (num_fish,) array of per-fish multiplicative gain
    draws (a frailty realization), SHARED across all of that fish's trials
    -- matching the modeling assumption that g_f is a fish-level, not a
    fish-trial-level, random effect. Defaults to gain=1 for every fish (no
    frailty).
    """
    if fish_gains is None:
        fish_gains = np.ones(scaffold.num_fish)

    times, trials, fish = [], [], []
    for f_idx in range(scaffold.num_fish):
        for t_idx in range(scaffold.num_trials):
            if not scaffold.fish_trial_mask[f_idx, t_idx]:
                continue
            ev = model.simulate_stream(scaffold, t_idx, float(fish_gains[f_idx]), rng)
            if len(ev):
                times.append(np.asarray(ev, dtype=float))
                trials.append(np.full(len(ev), t_idx, dtype=int))
                fish.append(np.full(len(ev), f_idx, dtype=int))

    event_times = np.concatenate(times) if times else np.array([], dtype=float)
    event_trials_idx = np.concatenate(trials) if trials else np.array([], dtype=int)
    event_fish_idx = np.concatenate(fish) if fish else np.array([], dtype=int)

    return PointProcessDataset(
        event_times=event_times,
        event_trials_idx=event_trials_idx,
        event_fish_idx=event_fish_idx,
        fish_trial_mask=scaffold.fish_trial_mask,
        fish_ids=scaffold.fish_ids,
        duration_s=scaffold.duration_s,
        binning_dt=scaffold.binning_dt,
    )


def dataset_from_streams(
    streams: List[List[np.ndarray]], duration_s: float, num_trials: int
) -> PointProcessDataset:
    """
    Build a PointProcessDataset from a nested list `streams[fish_idx][trial_idx]
    -> event_times array` -- used by Layer 2's independent-simulator tests,
    which don't go through simulate_dataset_from_model at all (that helper
    calls model.simulate_stream; Layer 2 deliberately avoids the model
    entirely on the generation side).
    """
    times, trials, fish = [], [], []
    for f_idx, per_trial_events in enumerate(streams):
        for t_idx, ev in enumerate(per_trial_events):
            if len(ev):
                times.append(np.asarray(ev, dtype=float))
                trials.append(np.full(len(ev), t_idx, dtype=int))
                fish.append(np.full(len(ev), f_idx, dtype=int))
    return PointProcessDataset(
        event_times=np.concatenate(times) if times else np.array([], dtype=float),
        event_trials_idx=np.concatenate(trials) if trials else np.array([], dtype=int),
        event_fish_idx=np.concatenate(fish) if fish else np.array([], dtype=int),
        fish_trial_mask=np.ones((len(streams), num_trials), dtype=bool),
        fish_ids=np.array([f"fish_{i}" for i in range(len(streams))]),
        duration_s=duration_s,
    )


# =============================================================================
# Assertion / introspection helpers
# =============================================================================


def assert_recovered(
    name: str, fitted: float, true: float, rtol: float = 0.15, atol: float = 0.02
):
    """
    Generic |fitted - true| <= atol + rtol*|true| check with a readable
    failure message. NOTE: this combines relative and absolute tolerance
    (like np.isclose) rather than pure relative, so tests on true values
    near zero (e.g. small dip depths) don't require an absurdly loose rtol.
    """
    diff = abs(fitted - true)
    tol = atol + rtol * abs(true)
    assert diff <= tol, (
        f"Parameter recovery failed for '{name}': fitted={fitted:.4f}, true={true:.4f}, "
        f"|diff|={diff:.4f} > tol={tol:.4f} (rtol={rtol}, atol={atol})"
    )


def params_dict(model) -> Dict[str, float]:
    return dict(zip(model.param_names, model.params_))


class DummyFitResult:
    """
    Minimal stand-in for scipy.optimize.OptimizeResult, used by Layer 3
    tests that evaluate time_rescaling() at TRUE parameters WITHOUT ever
    calling fit()/fit_multistart() -- some downstream consumers (e.g.
    diagnose()'s summary panel reading .log_likelihood) expect
    model.fit_result.fun to exist. Setting fun=nan is deliberate: it makes
    it obvious if a test accidentally relies on a real log-likelihood value
    from this dummy rather than computing one properly.
    """

    fun = float("nan")


# =============================================================================
# Common fixtures
# =============================================================================


@pytest.fixture
def rng_factory():
    """Returns a function that builds a fresh, seeded np.random.Generator --
    use rng_factory(seed) rather than a single shared fixture so each test
    can pick its own seed inline and stay independently reproducible/
    greppable without fixture indirection hiding the seed value."""

    def _make(seed: int) -> np.random.Generator:
        return np.random.default_rng(seed)

    return _make
