sbatch export.sbatch /ptmp/mapri/1010Kaede-X-81C/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/1010Kaede-X-81C/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/ccka/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/ccka/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/cort/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/cort/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/lak/danieau --no-videos
sbatch export.sbatch /ptmp/mapri/mafaa/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/mafaa/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/pmchl/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/pmchl/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/pth2/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/pth2/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/rspo1/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/rspo1/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/tbr1b/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/tbr1b/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/WT/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/WT/danieau --no-videos
sbatch export.sbatch /ptmp/mapri/itpr1b/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/itpr1b/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/pmch2/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/pmch2/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/atf5b/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/atf5b/vehicle --no-videos