sbatch export.sbatch /ptmp/mapri/1010Kaede-X-81C/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/1010Kaede-X-81C/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/ccka/ccka-vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/ccka/ccka-ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/cort/cort-vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/cort/cort-ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/lak --no-videos
sbatch export.sbatch /ptmp/mapri/mafaa/mafaa-vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/mafaa/mafaa-ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/pmchl/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/pmchl/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/pth2/pth2-vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/pth2/pth2-ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/rspo1/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/rspo1/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/tbr1b/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/tbr1b/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/WT/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/WT/danieau --no-videos
sbatch export.sbatch /ptmp/mapri/itpr1b/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/itpr1b/vehicle --no-videos
sbatch export.sbatch /ptmp/mapri/pmch2/ronidazole --no-videos
sbatch export.sbatch /ptmp/mapri/pmch2/vehicle --no-videos