sbatch megabout.sbatch /ptmp/mapri/1010Kaede-X-81C/vehicle
sbatch megabout.sbatch /ptmp/mapri/1010Kaede-X-81C/ronidazole
sbatch megabout.sbatch /ptmp/mapri/ccka/ccka-vehicle
sbatch megabout.sbatch /ptmp/mapri/ccka/ccka-ronidazole
sbatch megabout.sbatch /ptmp/mapri/cort/cort-vehicle
sbatch megabout.sbatch /ptmp/mapri/cort/cort-ronidazole
sbatch megabout.sbatch /ptmp/mapri/lak
sbatch megabout.sbatch /ptmp/mapri/mafaa/mafaa-vehicle
sbatch megabout.sbatch /ptmp/mapri/mafaa/mafaa-ronidazole
sbatch megabout.sbatch /ptmp/mapri/pmchl/vehicle
sbatch megabout.sbatch /ptmp/mapri/pmchl/ronidazole
sbatch megabout.sbatch /ptmp/mapri/pth2/pth2-vehicle
sbatch megabout.sbatch /ptmp/mapri/pth2/pth2-ronidazole
sbatch megabout.sbatch /ptmp/mapri/rspo1/vehicle
sbatch megabout.sbatch /ptmp/mapri/rspo1/ronidazole
sbatch megabout.sbatch /ptmp/mapri/tbr1b/vehicle
sbatch megabout.sbatch /ptmp/mapri/tbr1b/ronidazole
sbatch megabout.sbatch /ptmp/mapri/WT/ronidazole
sbatch megabout.sbatch /ptmp/mapri/WT/danieau
sbatch megabout.sbatch /ptmp/mapri/itpr1b/ronidazole
sbatch megabout.sbatch /ptmp/mapri/itpr1b/vehicle
sbatch megabout.sbatch /ptmp/mapri/pmch2/ronidazole
sbatch megabout.sbatch /ptmp/mapri/pmch2/vehicle
