sbatch megabout.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/ccka/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/ccka/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/cort/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/cort/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/lak/danieau
sbatch megabout.sbatch /ptmp/mapri/Screen/mafaa/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/mafaa/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/pmchl/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/pmchl/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/pth2/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/pth2/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/rspo1/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/rspo1/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/tbr1b/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/tbr1b/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/WT/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/WT/danieau
sbatch megabout.sbatch /ptmp/mapri/Screen/itpr1b/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/itpr1b/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/pmch2/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/pmch2/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/atf5b/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/atf5b/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/pcbp3/ronidazole
sbatch megabout.sbatch /ptmp/mapri/Screen/pcbp3/vehicle
sbatch megabout.sbatch /ptmp/mapri/Screen/chata/ronidazole 
sbatch megabout.sbatch /ptmp/mapri/Screen/chata/vehicle 
sbatch megabout.sbatch /ptmp/mapri/Screen/id2b/ronidazole 
sbatch megabout.sbatch /ptmp/mapri/Screen/id2b/vehicle 
sbatch megabout.sbatch /ptmp/mapri/Screen/lhx9/ronidazole 
sbatch megabout.sbatch /ptmp/mapri/Screen/lhx9/vehicle 
sbatch megabout.sbatch /ptmp/mapri/Screen/mafaa-switchNTR-ath5-Cre/ronidazole 
sbatch megabout.sbatch /ptmp/mapri/Screen/mafaa-switchNTR-ath5-Cre/vehicle 