sbatch plot.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/vehicle 
sbatch plot.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/ccka/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/ccka/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/cort/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/cort/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/lak/danieau
sbatch plot.sbatch /ptmp/mapri/Screen/mafaa/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/mafaa/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/pmchl/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/pmchl/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/pth2/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/pth2/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/rspo1/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/rspo1/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/tbr1b/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/tbr1b/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/WT/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/WT/danieau
sbatch plot.sbatch /ptmp/mapri/Screen/itpr1b/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/itpr1b/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/pmch2/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/pmch2/vehicle
sbatch plot.sbatch /ptmp/mapri/Screen/atf5b/ronidazole
sbatch plot.sbatch /ptmp/mapri/Screen/atf5b/vehicle
