sbatch qc.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/1026/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/1026/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/242A/ronidazole 
sbatch qc.sbatch /ptmp/mapri/Screen/242A/vehicle 
sbatch qc.sbatch /ptmp/mapri/Screen/AB/danieau
sbatch qc.sbatch /ptmp/mapri/Screen/atf5b/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/atf5b/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/cart2/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/cart2/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/ccka/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/ccka/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/chata/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/chata/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/cort/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/cort/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/gr/danieau 
sbatch qc.sbatch /ptmp/mapri/Screen/id2b/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/id2b/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/itpr1b/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/itpr1b/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/lak/danieau
sbatch qc.sbatch /ptmp/mapri/Screen/lhx9/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/lhx9/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/mafaa/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/mafaa/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/mafaa-switchNTR-ath5-Cre/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/mafaa-switchNTR-ath5-Cre/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/mecp2/danieau 
sbatch qc.sbatch /ptmp/mapri/Screen/pcbp3/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/pcbp3/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/pmch2/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/pmch2/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/pmchl/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/pmchl/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/pth2/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/pth2/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/rspo1/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/rspo1/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/tbr1b/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/tbr1b/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/tbr1b_run3/vehicle
sbatch qc.sbatch /ptmp/mapri/Screen/tbr1b_run3/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/wik/danieau 
sbatch qc.sbatch /ptmp/mapri/Screen/WT/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/WT/danieau
sbatch qc.sbatch /ptmp/mapri/Screen/y359/ronidazole 
sbatch qc.sbatch /ptmp/mapri/Screen/y359/vehicle 
sbatch qc.sbatch /ptmp/mapri/Screen/y532/ronidazole
sbatch qc.sbatch /ptmp/mapri/Screen/y532/vehicle 

