sbatch video_overlay.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/1010Kaede-X-81C/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/ccka/ccka-vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/ccka/ccka-ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/cort/cort-vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/cort/cort-ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/lak
sbatch video_overlay.sbatch /ptmp/mapri/Screen/mafaa/mafaa-vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/mafaa/mafaa-ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/pmchl/vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/pmchl/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/pth2/pth2-vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/pth2/pth2-ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/rspo1/vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/rspo1/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/tbr1b/vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/tbr1b/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/WT/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/WT/danieau
sbatch video_overlay.sbatch /ptmp/mapri/Screen/itpr1b/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/itpr1b/vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/pmch2/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/pmch2/vehicle
sbatch video_overlay.sbatch /ptmp/mapri/Screen/atf5b/ronidazole
sbatch video_overlay.sbatch /ptmp/mapri/Screen/atf5b/vehicle