data_config:
  train_labels_path:
  - /home/martin/Downloads/sleap/labels.v021.slp
  val_labels_path: null
  validation_fraction: 0.1
  test_file_path: null
  provider: LabelsReader
  user_instances_only: true
  data_pipeline_fw: torch_dataset
  cache_img_path: null
  use_existing_imgs: false
  delete_cache_imgs_after_training: true
  preprocessing:
    ensure_rgb: false
    ensure_grayscale: false
    max_height: 900
    max_width: 900
    scale: 1.0
    crop_size: 256
    min_crop_size: 100
  use_augmentations_train: true
  augmentation_config:
    intensity:
      uniform_noise_min: 0.0
      uniform_noise_max: 1.0
      uniform_noise_p: 0.1
      gaussian_noise_mean: 5.0
      gaussian_noise_std: 1.0
      gaussian_noise_p: 0.1
      contrast_min: 0.5
      contrast_max: 2.0
      contrast_p: 0.1
      brightness_min: 0.0
      brightness_max: 2.0
      brightness_p: 0.1
    geometric:
      rotation_min: -180.0
      rotation_max: 180.0
      scale_min: 0.9
      scale_max: 1.1
      translate_width: 0.0
      translate_height: 0.0
      affine_p: 1.0
      erase_scale_min: 0.0001
      erase_scale_max: 0.01
      erase_ratio_min: 1.0
      erase_ratio_max: 1.0
      erase_p: 0.0
      mixup_lambda_min: 0.01
      mixup_lambda_max: 0.05
      mixup_p: 0.0
  skeletons:
  - nodes:
    - name: Head
    - name: Eye_Left_Front
    - name: Eye_Left_Back
    - name: Eye_Right_Front
    - name: Eye_Right_Back
    - name: Swim_Bladder
    - name: Tail_0
    - name: Tail_1
    - name: Tail_2
    - name: Tail_3
    - name: Tail_4
    - name: Tail_5
    - name: Tail_6
    - name: Tail_7
    - name: Tail_8
    - name: Tail_9
    edges:
    - source:
        name: Head
      destination:
        name: Swim_Bladder
    - source:
        name: Swim_Bladder
      destination:
        name: Tail_0
    - source:
        name: Tail_0
      destination:
        name: Tail_1
    - source:
        name: Tail_1
      destination:
        name: Tail_2
    - source:
        name: Tail_2
      destination:
        name: Tail_3
    - source:
        name: Tail_3
      destination:
        name: Tail_4
    - source:
        name: Tail_4
      destination:
        name: Tail_5
    - source:
        name: Tail_5
      destination:
        name: Tail_6
    - source:
        name: Tail_6
      destination:
        name: Tail_7
    - source:
        name: Tail_7
      destination:
        name: Tail_8
    - source:
        name: Tail_8
      destination:
        name: Tail_9
    - source:
        name: Eye_Left_Front
      destination:
        name: Eye_Left_Back
    - source:
        name: Eye_Right_Front
      destination:
        name: Eye_Right_Back
    - source:
        name: Head
      destination:
        name: Eye_Left_Front
    - source:
        name: Head
      destination:
        name: Eye_Left_Back
    - source:
        name: Head
      destination:
        name: Eye_Right_Front
    - source:
        name: Head
      destination:
        name: Eye_Right_Back
    - source:
        name: Eye_Right_Back
      destination:
        name: Swim_Bladder
    - source:
        name: Eye_Left_Back
      destination:
        name: Swim_Bladder
    symmetries: []
    name: null
model_config:
  init_weights: default
  pretrained_backbone_weights: null
  pretrained_head_weights: null
  backbone_config:
    unet:
      in_channels: 1
      kernel_size: 3
      filters: 48
      filters_rate: 2.0
      max_stride: 64
      stem_stride: null
      middle_block: true
      up_interpolate: true
      stacks: 1
      convs_per_block: 2
      output_stride: 4
    convnext: null
    swint: null
  head_configs:
    single_instance: null
    centroid: null
    centered_instance:
      confmaps:
        part_names:
        - Head
        - Eye_Left_Front
        - Eye_Left_Back
        - Eye_Right_Front
        - Eye_Right_Back
        - Swim_Bladder
        - Tail_0
        - Tail_1
        - Tail_2
        - Tail_3
        - Tail_4
        - Tail_5
        - Tail_6
        - Tail_7
        - Tail_8
        - Tail_9
        anchor_part: Swim_Bladder
        sigma: 2.5
        output_stride: 4
        loss_weight: 1.0
    bottomup: null
    multi_class_bottomup: null
    multi_class_topdown: null
  total_params: 282673888
trainer_config:
  train_data_loader:
    batch_size: 4
    shuffle: false
    num_workers: 0
  val_data_loader:
    batch_size: 4
    shuffle: false
    num_workers: 0
  model_ckpt:
    save_top_k: 1
    save_last: false
  trainer_devices: auto
  trainer_device_indices: null
  trainer_accelerator: auto
  profiler: null
  trainer_strategy: auto
  enable_progress_bar: true
  min_train_steps_per_epoch: 200
  train_steps_per_epoch: 200
  visualize_preds_during_training: true
  keep_viz: false
  max_epochs: 200
  seed: null
  use_wandb: false
  save_ckpt: true
  ckpt_dir: /home/martin/Downloads/sleap/models
  run_name: 251018_000000.centered_instance.n=632
  resume_ckpt_path: null
  wandb:
    entity: ''
    project: ''
    name: ''
    save_viz_imgs_wandb: false
    api_key: ''
    wandb_mode: null
    prv_runid: ''
    group: ''
    current_run_id: null
  optimizer_name: Adam
  optimizer:
    lr: 0.0001
    amsgrad: false
  lr_scheduler: null
  early_stopping:
    min_delta: 1.0e-08
    patience: 10
    stop_training_on_plateau: true
  online_hard_keypoint_mining:
    online_mining: true
    hard_to_easy_ratio: 2.0
    min_hard_keypoints: 2
    max_hard_keypoints: null
    loss_scale: 5.0
  zmq:
    controller_port: 9000
    controller_polling_timeout: 10
    publish_port: 9001
name: ''
description: ''
sleap_nn_version: 0.0.2
filename: ''
