sbatch plot.sbatch /ptmp/mapri/1010Kaede-X-81C/vehicle 
sbatch plot.sbatch /ptmp/mapri/1010Kaede-X-81C/ronidazole
sbatch plot.sbatch /ptmp/mapri/ccka/ccka-vehicle
sbatch plot.sbatch /ptmp/mapri/ccka/ccka-ronidazole
sbatch plot.sbatch /ptmp/mapri/cort/cort-vehicle
sbatch plot.sbatch /ptmp/mapri/cort/cort-ronidazole
sbatch plot.sbatch /ptmp/mapri/lak
sbatch plot.sbatch /ptmp/mapri/mafaa/mafaa-vehicle
sbatch plot.sbatch /ptmp/mapri/mafaa/mafaa-ronidazole
sbatch plot.sbatch /ptmp/mapri/pmchl/vehicle
sbatch plot.sbatch /ptmp/mapri/pmchl/ronidazole
sbatch plot.sbatch /ptmp/mapri/pth2/pth2-vehicle
sbatch plot.sbatch /ptmp/mapri/pth2/pth2-ronidazole
sbatch plot.sbatch /ptmp/mapri/rspo1/vehicle
sbatch plot.sbatch /ptmp/mapri/rspo1/ronidazole
sbatch plot.sbatch /ptmp/mapri/tbr1b/vehicle
sbatch plot.sbatch /ptmp/mapri/tbr1b/ronidazole
sbatch plot.sbatch /ptmp/mapri/WT/ronidazole
sbatch plot.sbatch /ptmp/mapri/WT/danieau
sbatch plot.sbatch /ptmp/mapri/itpr1b/ronidazole
sbatch plot.sbatch /ptmp/mapri/itpr1b/vehicle
sbatch plot.sbatch /ptmp/mapri/pmch2/ronidazole
sbatch plot.sbatch /ptmp/mapri/pmch2/vehicle
