sbatch Slurm/video_overlay.sbatch /ptmp/mapri/1010Kaede-X-81C/vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/1010Kaede-X-81C/ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/ccka/ccka-vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/ccka/ccka-ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/cort/cort-vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/cort/cort-ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/lak
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/mafaa/mafaa-vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/mafaa/mafaa-ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/pmchl/vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/pmchl/ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/pth2/pth2-vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/pth2/pth2-ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/rspo1/vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/rspo1/ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/tbr1b/vehicle
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/tbr1b/ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/WT/ronidazole
sbatch Slurm/video_overlay.sbatch /ptmp/mapri/WT/danieau