python -m BehaviorScreen.merge_csv /media/martin/DATA_18TB/Screen \
-o bouts_control.csv \
ccka/vehicle/bouts.csv \
lhx9/vehicle/bouts.csv \
y532/vehicle/bouts.csv \
pth2/vehicle/bouts.csv \
itpr1b/vehicle/bouts.csv \
chata/vehicle/bouts.csv \
1026/vehicle/bouts.csv \
cart2/vehicle/bouts.csv \
opn4b/vehicle/bouts.csv \
WT/danieau/bouts.csv \
WT/ronidazole/bouts.csv \
WT/vehicle/bouts.csv \
tbr1b_run3/vehicle/bouts.csv \
gbx/vehicle/bouts.csv \
mpn310/vehicle/bouts.csv \
tbr1b/vehicle/bouts.csv \
pmchl/vehicle/bouts.csv \
rspo1/vehicle/bouts.csv \
gfra/vehicle/bouts.csv \
drd2a/vehicle/bouts.csv \
isl1/vehicle/bouts.csv \
atf5b/vehicle/bouts.csv \
mafaa-switchNTR-Huc-Cre/vehicle/bouts.csv \
mpn206/vehicle/bouts.csv \
th/vehicle/bouts.csv \
mpn302/vehicle/bouts.csv \
mafaa/vehicle/bouts.csv \
242A/vehicle/bouts.csv \
pmch2/vehicle/bouts.csv \
1010/vehicle/bouts.csv \
y359/vehicle/bouts.csv \
mafaa-switchNTR-ath5-Cre/vehicle/bouts.csv \
insm2/vehicle/bouts.csv \
id2b/vehicle/bouts.csv \
pcbp3/vehicle/bouts.csv \
cort/vehicle/bouts.csv \
lhx2b/vehicle/bouts.csv \
mpn318/vehicle/bouts.csv --no-header-check


python -m BehaviorScreen.merge_csv /media/martin/DATA_18TB/Screen \
-o qc.csv \
ccka/vehicle/qc.csv \
lhx9/vehicle/qc.csv \
y532/vehicle/qc.csv \
pth2/vehicle/qc.csv \
itpr1b/vehicle/qc.csv \
chata/vehicle/qc.csv \
1026/vehicle/qc.csv \
cart2/vehicle/qc.csv \
opn4b/vehicle/qc.csv \
WT/danieau/qc.csv \
WT/ronidazole/qc.csv \
WT/vehicle/qc.csv \
tbr1b_run3/vehicle/qc.csv \
gbx/vehicle/qc.csv \
mpn310/vehicle/qc.csv \
tbr1b/vehicle/qc.csv \
pmchl/vehicle/qc.csv \
rspo1/vehicle/qc.csv \
gfra/vehicle/qc.csv \
drd2a/vehicle/qc.csv \
isl1/vehicle/qc.csv \
atf5b/vehicle/qc.csv \
mafaa-switchNTR-Huc-Cre/vehicle/qc.csv \
mpn206/vehicle/qc.csv \
th/vehicle/qc.csv \
mpn302/vehicle/qc.csv \
mafaa/vehicle/qc.csv \
242A/vehicle/qc.csv \
pmch2/vehicle/qc.csv \
1010/vehicle/qc.csv \
y359/vehicle/qc.csv \
mafaa-switchNTR-ath5-Cre/vehicle/qc.csv \
insm2/vehicle/qc.csv \
id2b/vehicle/qc.csv \
pcbp3/vehicle/qc.csv \
cort/vehicle/qc.csv \
lhx2b/vehicle/qc.csv \
mpn318/vehicle/qc.csv 

python -m BehaviorScreen.merge_csv /media/martin/DATA_18TB/Screen \
-o valid_trials.csv \
ccka/vehicle/valid_trials.csv \
lhx9/vehicle/valid_trials.csv \
y532/vehicle/valid_trials.csv \
pth2/vehicle/valid_trials.csv \
itpr1b/vehicle/valid_trials.csv \
chata/vehicle/valid_trials.csv \
1026/vehicle/valid_trials.csv \
cart2/vehicle/valid_trials.csv \
opn4b/vehicle/valid_trials.csv \
WT/danieau/valid_trials.csv \
WT/ronidazole/valid_trials.csv \
WT/vehicle/valid_trials.csv \
tbr1b_run3/vehicle/valid_trials.csv \
gbx/vehicle/valid_trials.csv \
mpn310/vehicle/valid_trials.csv \
tbr1b/vehicle/valid_trials.csv \
pmchl/vehicle/valid_trials.csv \
rspo1/vehicle/valid_trials.csv \
gfra/vehicle/valid_trials.csv \
drd2a/vehicle/valid_trials.csv \
isl1/vehicle/valid_trials.csv \
atf5b/vehicle/valid_trials.csv \
mafaa-switchNTR-Huc-Cre/vehicle/valid_trials.csv \
mpn206/vehicle/valid_trials.csv \
th/vehicle/valid_trials.csv \
mpn302/vehicle/valid_trials.csv \
mafaa/vehicle/valid_trials.csv \
242A/vehicle/valid_trials.csv \
pmch2/vehicle/valid_trials.csv \
1010/vehicle/valid_trials.csv \
y359/vehicle/valid_trials.csv \
mafaa-switchNTR-ath5-Cre/vehicle/valid_trials.csv \
insm2/vehicle/valid_trials.csv \
id2b/vehicle/valid_trials.csv \
pcbp3/vehicle/valid_trials.csv \
cort/vehicle/valid_trials.csv \
lhx2b/vehicle/valid_trials.csv \
mpn318/vehicle/valid_trials.csv 
